; PlatformIO Project Configuration File for Seeed Studio XIAO ESP32S3 Sense

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

board_build.arduino.memory_type = qio_opi
board_build.partitions = default_8MB.csv

monitor_speed = 115200
upload_speed = 921600

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCONFIG_SPIRAM_CACHE_WORKAROUND
    -DCORE_DEBUG_LEVEL=3

lib_deps =
    espressif/esp32-camera @ ^2.0.4
    bblanchon/ArduinoJson @ ^7.0.4
    me-no-dev/ESP Async WebServer @ ^1.2.4
    me-no-dev/AsyncTCP @ ^1.1.1

; pio test -e native
[env:native]
platform = native
test_framework = unity
build_src_filter = -<*>
